### ISSUE TITLE
ES6 compatibility

### ISSUE THREAD

**Issue by cshaa** [loverajoel/timeance.js#3]
It says "ES6 compatible" – but wait! How can you make an _ES6 incompatible_ version? EcmaScript is backwards compatible – even ES3 is valid ES6!

**Comment by loverajoel** [comment]
@m93a there are a [branch](https://github.com/loverajoel/timeance.js/tree/es6) written in ES6, maybe, it should say "ES6 version available", what do you think?

**Comment by cshaa** [comment]
Yeah, that would be less misleading :)
